### ISSUE TITLE
 The command '/bin/sh -c apk update' returned a non-zero code: 139

### ISSUE THREAD

**Issue by quii** [gliderlabs/docker-alpine#180] opened 2016-06-02 09:10 UTC
I get the error message `The command '/bin/sh -c apk update' returned a non-zero code: 139` when I run the following dockerfile

```
FROM gliderlabs/alpine:3.3
RUN apk update
RUN apk add curl bash
```

This is running on ubuntu 16. I recently changed my kernel version which I initially thought was the problem but running other images seems to be fine, so I dont _think_ this is the issue.

Any ideas?

**Comment by johanbrandhorst** [comment] 2016-06-08 08:42
Seeing the exact same problem on 16.04 with kernel 4.6.0-040600-generic #201606030904. Not sure if it's related to alpine.

**Comment by thuandt** [comment] 2016-06-17 12:59
I have same problem. I reported it in docker repos https://github.com/docker/docker/issues/23471

**Comment by nrvale0** [comment] 2016-08-31 19:12
I'm actually getting a 139/SIGSEGV with a much more simple invocation on Alpine:

```ShellSession
➜  /tmp docker run -ti --entrypoint=/bin/sh alpine /bin/sh
➜  /tmp echo $?
139
```

I've added more context on docker/docker#23471 as well.

**Comment by andyshinn** [comment] 2016-09-30 17:39
I can't reproduce this on Docker 1.12.1. Is this still an issue?

```console
root@ubuntu16:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
root@ubuntu16:~# uname -a
Linux ubuntu16 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu16:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
root@ubuntu16:~# docker pull alpine:latest && docker run -ti alpine:latest /bin/sh
latest: Pulling from library/alpine
Digest: sha256:ca7b185775966003d38ccbd9bba822fb570766e4bb69292ac23490f36f8a742e
Status: Image is up to date for alpine:latest
/ # echo "Hi from Alpine"
Hi from Alpine
/ # exit
root@ubuntu16:~#
```

**Comment by nrvale0** [comment] 2016-09-30 18:10
Still busted for me:

```ShellSession
➜  ~ docker --version
Docker version 1.12.1, build 23cf638
➜  ~ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
➜  ~ uname -a
Linux atacama 4.6.7-xanmod9 #1 SMP Thu Aug 18 01:45:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ docker pull alpine:latest && docker run -ti alpine:latest /bin/sh
latest: Pulling from library/alpine

c0cb142e4345: Pull complete 
Digest: sha256:ca7b185775966003d38ccbd9bba822fb570766e4bb69292ac23490f36f8a742e
Status: Downloaded newer image for alpine:latest
➜  ~ echo $?
139
```

**Comment by andyshinn** [comment] 2016-09-30 19:45
Is it related to the XanMod kernel per https://forum.xanmod.org/thread-55.html? Are you able to try kernel 4.7 per the last post?

**Comment by nrvale0** [comment] 2016-10-07 02:17
I installed latest 4.8-based xanmod and now the above command works.

**Comment by andyshinn** [comment] 2016-11-09 01:48
Going to close this as it is related to a custom kernel which we can't really support or account for. It sounds like later versions of this kernel are working better with Docker.

**Closed by andyshinn** 2016-11-09 01:48 UTC
Labels: bug, invalid, question, upstream, wontfix

**Comment by FlorianHeigl** [comment] 2016-12-15 00:00
```
root@zz:~/rvm-package# dpkg -l | grep docker
ii  docker.io                      1.12.1-0ubuntu13~16.04.1           arm64        Linux container runtime
root@zz:~/rvm-package# uname -a
Linux zz.local.lan 4.4.0-38-generic #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux
```

```
root@zz:~/rvm-package# docker build -t rvm-package .
Sending build context to Docker daemon 69.63 kB
Step 1 : FROM ajeetraina/centos7-arm
latest: Pulling from ajeetraina/centos7-arm
5584ea4c92c5: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:10989b1b7a3bdf826857ba5b3348956d495b9be1ced644a3aa7321cfbd705b04
Status: Downloaded newer image for ajeetraina/centos7-arm:latest
 ---> 495db0a341d8
Step 2 : MAINTAINER Petr Archakov <petr.etc@gmail.com>
 ---> Running in 0ff448edc7a5
 ---> b5183f89eeaf
Removing intermediate container 0ff448edc7a5
Step 3 : RUN yum install -y wget curl tar make gcc-c++ rpm-build nano which   libyaml-devel autoconf readline-devel zlib-devel libffi-devel openssl-devel   automake libtool bison sqlite-devel
 ---> Running in 773809bcf027
The command '/bin/sh -c yum install -y wget curl tar make gcc-c++ rpm-build nano which   libyaml-devel autoconf readline-devel zlib-devel libffi-devel openssl-devel   automake libtool bison sqlite-devel' returned a non-zero code: 139
```
i *think* this thing is running the standard kernel.

```
root@zz:~/rvm-package# dpkg -l | grep linux-
ii  linux-base                     4.0ubuntu1                         all          Linux image base package
```

**Comment by FlorianHeigl** [comment] 2016-12-15 00:00
it's a cavium box at packet.net, you can reproduce there quite easily.

**Comment by zw963** [comment] 2018-04-22 03:38
> Seeing the exact same problem on 16.04 with kernel 4.6.0-040600-generic #201606030904. Not sure if it's related to alpine.
> 
> EDIT: Running fine on 4.4.0-23-generic #41-Ubuntu

Hi, I am not use alpine,  following is my host info:

```sh
$: uname -a
Linux zw963-PC 4.14.0-deepin2-amd64 #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux
```

I got exact same error in this system, but same Dockerfile, it worked in my another linux laptop (4.4.115)

**Comment by zw963** [comment] 2018-04-22 03:42
@andyshinn ,  @johanbrandhorst , do you think this is a issue which still not fixed?

**Comment by johanbrandhorst** [comment] 2018-04-22 06:51
I haven't seen it for ages but I'm not using kernel 4.6 anymore either.
