### ISSUE TITLE
How can I install script command in alpine

### ISSUE THREAD

**Issue by kooksee** [gliderlabs/docker-alpine#160] opened 2016-04-09 09:48 UTC
I like tiny alpine very much, while I can't install script command in alpine. when I am working on the terminal,I  record what I have done in the terminal. but now ,feel little sad.

**Comment by andyshinn** [comment] 2016-04-09 15:58
Can you give an example of what you are trying to do?

**Comment by snc** [comment] 2016-04-10 07:39
Just install the `util-linux` package and you will get the `script` command.

**Comment by andyshinn** [comment] 2016-11-09 01:42
Closing as this has been answered. If the previous answer isn't working then please reopen.

**Closed by andyshinn** 2016-11-09 01:42 UTC
Labels: question

**Comment by ogbofjnr** [comment] 2020-06-05 08:36
The problem is that installing it will take 350mb, which make no sense of using alpine. Is there a way to install only one command?

**Comment by ITJamie** [comment] 2022-04-06 13:53
+1 on script being in a massive package. would be nice to see it get split

**Comment by ericwq** [comment] 2023-09-27 02:33
try util-linux-misc, it's 3.7mb.
