### ISSUE TITLE
Marshmallow  for lg stylio

### ISSUE THREAD

**Issue by obsservationsmade3** [gliderlabs/docker-alpine#126] opened 2015-12-26 19:25 UTC

**Comment by jumanjiman** [comment] 2015-12-26 19:30
dupe of https://github.com/gliderlabs/docker-alpine/issues/124

is this a real account?

![screenshot 2015-12-26 at 14 29 34](https://cloud.githubusercontent.com/assets/332496/12007682/290d24da-abdd-11e5-981d-194f5de6f16d.png)

**Closed** 2015-12-26 20:07 UTC
