### ISSUE TITLE
503 Backend is unhealthy

### ISSUE THREAD

**Issue by cyrilfr** [gliderlabs/docker-alpine#394] opened 2018-03-19 13:43 UTC
```
Step 2/15 : RUN apk --update add bash
---> Running in b46c1ce6a802
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
```

**Comment by cilindrox** [comment] 2018-03-19 13:44
Same here with several other packages (`tini`, `python`, `make`). Seems like an issue with the CDN?

**Comment by cilindrox** [comment] 2018-03-19 13:45
This seems to be a dupe of #386

**Comment by pureclouds** [comment] 2018-03-19 13:47
the same for me

```
curl -v -s http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz -o /dev/null -I
*   Trying 151.101.112.249...
* Connected to dl-cdn.alpinelinux.org (151.101.112.249) port 80 (#0)
> HEAD /alpine/edge/main/x86_64/APKINDEX.tar.gz HTTP/1.1
> Host: dl-cdn.alpinelinux.org
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 503 Backend is unhealthy
< Server: Varnish
< Retry-After: 0
< Content-Type: text/html; charset=utf-8
< Content-Length: 454
< Accept-Ranges: bytes
< Date: Mon, 19 Mar 2018 13:45:38 GMT
< Via: 1.1 varnish
< Connection: close
< X-Served-By: cache-hhn1524-HHN
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1521467138.045334,VS0,VE0
<
* Closing connection 0

```

**Comment by cyrilfr** [comment] 2018-03-19 13:47
And [#351](https://github.com/gliderlabs/docker-alpine/issues/351)

**Comment by bat-cha** [comment] 2018-03-19 13:52
it's back up for me...

**Comment by maishsk** [comment] 2018-03-19 13:53
Same here

**Comment by wsantos** [comment] 2018-03-19 13:53
Confirmed, it's back.

**Comment by maprager** [comment] 2018-03-19 13:57
and me - back up:

 curl -v -s http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz -o /dev/null -I
*   Trying 151.101.0.249...
* TCP_NODELAY set
* Connected to dl-cdn.alpinelinux.org (151.101.0.249) port 80 (#0)
> HEAD /alpine/edge/main/x86_64/APKINDEX.tar.gz HTTP/1.1
> Host: dl-cdn.alpinelinux.org
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< ETag: "5aafb378-bf941"
< Accept-Ranges: bytes
< Accept-Ranges: bytes
< Date: Mon, 19 Mar 2018 13:52:17 GMT
< X-Served-By: cache-fra19137-FRA
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1521467538.675278,VS0,VE42
< Content-Length: 784705
< Content-Type: application/octet-stream
< Last-Modified: Mon, 19 Mar 2018 12:56:24 GMT
< Via: ....
< Connection: keep-alive
<
* Connection #0 to host dl-cdn.alpinelinux.org left intact

**Comment by cyrilfr** [comment] 2018-03-19 14:19
Still down for me.

**Comment by siebertm** [comment] 2018-03-19 14:22
still flaky. sometimes requests go through, sometimes they don't.

**Comment by MarienLbc** [comment] 2018-03-19 14:22
Same as @cyrilfr  but i'm on v3.6

**Comment by brejnko** [comment] 2018-03-19 14:23
Before was 503 Backend is unhealthy now I get  503 Connection timed out.

**Comment by jangia** [comment] 2018-03-19 14:25
Down for me too

**Comment by AndriiHryshaienko** [comment] 2018-03-19 14:45
Looks like its working now.

**Comment by MarienLbc** [comment] 2018-03-19 15:17
Seems ok too !

**Comment by zilongqiu** [comment] 2018-03-19 17:11
Same problem for me :/

**Comment by chrisweeksnz** [comment] 2018-03-22 01:02
Seems like the cdn availability is extremely variable  :\

Down again at the moment.

**Comment by jangia** [comment] 2018-03-22 01:05
It's down again

**Comment by ncopa** [comment] 2018-05-14 19:17
we have replaced the dl-cdn backend to something we believe will be more stable. We have in addition also configure a failover that will take over if backend is unavailable.

**Closed by ncopa** 2018-05-14 19:17 UTC

**Comment by jovanimp** [comment] 2018-07-05 05:19
Hi all,
I get the same error now 
Error 503 Backend is unhealthy
Backend is unhealthy
Guru Mediation:
Details: cache-ams4128-AMS 1530767897 492878393

Varnish cache server

**Comment by radiocity** [comment] 2018-07-05 07:01
Looks like the github problem (githubusercontent.com)

**Comment by k-kackey0-1** [comment] 2022-02-15 02:16
Hi All 
I got also same error now. Any idea ?
```
Error 503 Backend is unhealthy
Backend is unhealthy

Guru Mediation:
Details: cache-tyo11935-TYO 1644891005 1365150189

Varnish cache server
```
