### ISSUE TITLE
alpine:latest: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by nailgun** [gliderlabs/docker-alpine#422] opened 2018-07-06 13:12 UTC
```
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by kit-ty-kate** [comment] 2018-07-06 13:20
yep, we've been hit by the same problem for [ocaml/opam-repository](https://github.com/ocaml/opam-repository/)'s CI :/

**Comment by kit-ty-kate** [comment] 2018-07-06 13:23
This issue is probably duplicated with #418 though

**Comment by CowChris** [comment] 2018-07-06 13:46
+1, exact same output.

**Comment by ledor473** [comment] 2018-07-06 14:11
Same result with 3.8
```
docker pull alpine:3.8                    
3.8: Pulling from library/alpine
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by rodrigocostasensedia** [comment] 2018-07-06 14:18
+1, exact same output. Tested with Amazon Linux and Centos 7.5.1804.

**Comment by tianon** [comment] 2018-07-06 14:41
Duplicate of https://github.com/gliderlabs/docker-alpine/issues/418

**Closed by tianon** 2018-07-06 14:41 UTC
