### ISSUE TITLE
Alpine 3.9 version available

### ISSUE THREAD

**Issue by bastijns-jeroen** [gliderlabs/docker-alpine#477] opened 2019-01-28 10:17 UTC
Hi,

Is it possible to release version 3.9 of Alpine as a docker tag? It is currently available in the 'edge' tag, but I prefer to depend on a real version number.

Thanks in advance!

**Comment by ncopa** [comment] 2019-01-28 15:15
this is a dupe of #471

**Comment by ViltusVilks** [comment] 2019-01-30 04:14
As I understand  EDGE is not so edge from docker image point of view. 
Probably packages will be... but not the rootfs.

https://github.com/gliderlabs/docker-alpine/commit/daf08505ee002002c660f94745d505e2a38ff40a
rootfs dated Dec21 and always copied to base

**Closed** 2019-02-08 13:24 UTC
