### ISSUE TITLE
apk fails to update/add.

### ISSUE THREAD

**Issue by bddenhartog** [gliderlabs/docker-alpine#55] opened 2015-07-26 22:03 UTC
Hey there!

I'm new to docker, and new to alpine in general. I love the work you've done and think it's fantastic for a container-centric future. I'm running into issues using `apk update` and `apk add`, in addition to `apk-install` using the base image provided by `gliderlabs/docker-alpine:3.1` (and `:3.2`, for that matter).

Using a `Dockerfile` that looks like:

    FROM gliderlabs/alpine:3.1
    RUN apk --update add mysql-client
    ENTRYPOINT ["mysql"]

I get this error:

    Step 1 : RUN apk --update add mysql-client
     ---> Running in 9129d237031e
    fetch http://dl-4.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
    ERROR: http://dl-4.alpinelinux.org/alpine/v3.1/main: IO ERROR
    WARNING: Ignoring APKINDEX.689bb31a.tar.gz: No such file or directory
    ERROR: unsatisfiable constraints:
      mysql-client (missing):
        required by: world[mysql-client]
    The command '/bin/sh -c apk --update add mysql-client' returned a non-zero code: 1

After doing some research (which was rather annoying, as the Alpine Linux wiki is down -- yay google cache and archive.org), everything I was attempting to do seemed to be correct. 

Logically, I figured it was an issue with the repository sources. No problem, let's open up `/etc/apk/repositores`. 

Whoops! It looks like by default, you only have `http://dl-4.alpinelinux.org/alpine/v3.1/main`. I ran into #15 and discovered a list of mirrors which have been most helpful. It currently looks like the following sources are *currently* failing:

    http://dl-3.alpinelinux.org/alpine/v3.1/main
    http://dl-4.alpinelinux.org/alpine/v3.1/main

1, 2, and 5 are peachy. I propose adding mirrors to the repositories included in your base image. While it's easy enough for people to add the mirrors themselves, it will save time in the long run, especially for newer users.

Edit (next day): 3 and 4 back up. It would seem the logical choice to add all five mirrors by default.

**Comment by jckimble** [comment] 2015-08-27 01:08
try to add
RUN echo "ipv6" >> /etc/modules
in your dockerfile before apk update, Its working for me, I'm going to do a pull request if it fixes it for somebody else

**Comment by bddenhartog** [comment] 2015-08-27 01:09
@jckimble as i noted, it was due to the repositories literally being offline.

**Comment by jckimble** [comment] 2015-08-27 01:56
oh sorry, I was using dl-4 earlier today and that fixed it for me, I guess it came back up between yesterday and today

**Comment by bddenhartog** [comment] 2015-08-27 02:01
@jckimble: I created this issue on July 26 2015. The issue, as I discovered, was simply that the alpine base image (not just gliderlabs' -- but the base alpine:3.2 image) only contains the dl-3 and dl-4 repositories.

On the day that I reported the issue, at the time I reported it, dl-3 and dl-4 were both failing to respond, causing apk update/add commands to hang until failure. I edited the post on the next day, July 26 2015, and noted that dl-3 and dl-4 were back online.

I'm leaving this issue open for two reasons.

1. So that others who may run into the same issue can understand *why* it is occurring and *how* to resolve it, and

2. So that gliderlabs may decide to add 1,2, and 5 as sources to their image so that this issue can be better mitigated.

**Comment by jckimble** [comment] 2015-08-27 04:14
https://github.com/gliderlabs/docker-alpine/pull/61 Pull Request to add all mirrors

**Comment by andyshinn** [comment] 2015-09-08 06:13
When you fixed the problem by adding additional repositories, did you add them under dl-4 and observe that dl-4 would fail and then go to the next repository? This is definitely related to #55 and I think we will get a couple more repositories to the list. But I've had mixed reports of how it actually fails over and want to understand it a bit more first.

**Comment by bddenhartog** [comment] 2015-09-08 06:57
@andyshinn I added dl-1 through dl-5 in order; that is to say:

```
http://dl-1.alpinelinux.org/alpine/v3.2/main
http://dl-2.alpinelinux.org/alpine/v3.2/main
http://dl-3.alpinelinux.org/alpine/v3.2/main
http://dl-4.alpinelinux.org/alpine/v3.2/main
http://dl-5.alpinelinux.org/alpine/v3.2/main
```

When it got to `dl-3`, it hung for a while, errored out, and then moved to `dl-4`, which hung, errored, and moved to `dl-5`. The above is what I put as my sources in images based on `alpine:3.2` (the official release), and I haven't had issues yet. This leads me to the conclusion that as long as one of the repositories listed in `/etc/apk/repositories` is up, the user should be able to run apk commands successfully.

**Comment by tilgovi** [comment] 2015-09-08 15:18
My experience is that a timeout does not fail over.

**Comment by envygeeks** [comment] 2015-09-08 19:18
Yup, I have the same problem as @tilgovi, for us it doesn't fail over, apk just sits there for however long it takes me to get pissed off and kill it to test it locally, I've never even got a timeout error from apk.

**Comment by tilgovi** [comment] 2015-09-08 19:31
I've seen evidence around that apk does use multiple mirrors when they are defined. I've also observed that if I put in something that's totally not right that apk will ignore the "bad" mirror.

I can't remember the exact message I saw, but at the time things were very intermittent and slow from dl-4. Individual packages would timeout, sometimes mid-download, and then apk would not retry with a different mirror. That may be an issue for upstream, but in the meantime I suspect that doing something to address the reliability would help us here a lot.

**Comment by andyshinn** [comment] 2015-09-08 20:39
Right, this has been my experience as well and is why I'm not jumping to add more mirrors to the list. I'd rather learn more about what we expect behavior to be so I can open an issue upstream. It's also possible that it is *supposed* to failover or timeout on bad network / packet loss but is just a bug.

And yes, I meant that this is related to #61 (and probably #66 as well) :stuck_out_tongue:.

I'm going to close this in favor of #61, #66, and #4. It seems like this issue is a mix of fixes from those pull requests. Feel free to comment in those and /or re-open this if I am missing something here.

**Closed by andyshinn** 2015-09-08 20:39 UTC
Labels: question

**Comment by trompx** [comment] 2015-12-07 08:50
Hello,

I post here because what I am seeing is exactly what was originally posted here (not in the other issues). In my Dockerfile I have :

```
FROM alpine:3.2
ADD repositories /etc/apk/repositories
RUN apk --update add nginx
```

And it has been 2 days I get the following errors :
```
Step 1 : FROM alpine:3.2
 ---> 5f36db706cc4
Step 2 : ADD repositories /etc/apk/repositories
 ---> dde067180c33
Step 3 : RUN apk --update add nginx
 ---> Running in 94322b25a762
fetch http://dl-1.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-1.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.e10619d8.tar.gz: No such file or directory
fetch http://dl-2.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-2.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.72be7668.tar.gz: No such file or directory
fetch http://dl-3.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-3.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.2f76b101.tar.gz: No such file or directory
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-4.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.abd86498.tar.gz: No such file or directory
fetch http://dl-5.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-5.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.d195cb40.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  nginx (missing):
    required by: world[nginx]
The command '/bin/sh -c apk --update add nginx' returned a non-zero code: 1
```
I can ping totally fine both repositories from the virtualbox VM where I run the build command..

**Comment by miry** [comment] 2015-12-07 09:37
I have same problem.

```
FROM alpine:edge
MAINTAINER PubNative Team <team@pubnative.net>

RUN echo "ipv6" >> /etc/modules
RUN echo "http://dl-1.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories; \
    echo "http://dl-2.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories; \
    echo "http://dl-3.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories; \
    echo "http://dl-4.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories; \
    echo "http://dl-5.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
```

```
$ docker run -it go sh
/ # apk update
fetch http://dl-4.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-1.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-2.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-3.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-5.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
v3.3.0_rc1-143-gdad8488 [http://dl-4.alpinelinux.org/alpine/edge/main]
v3.3.0_rc1-140-g1fe0ee3 [http://dl-1.alpinelinux.org/alpine/edge/main]
v3.3.0_rc1-3-gbd9bf58 [http://dl-2.alpinelinux.org/alpine/edge/main]
v3.3.0_rc1-143-gdad8488 [http://dl-3.alpinelinux.org/alpine/edge/main]
v3.3.0_rc1-143-gdad8488 [http://dl-5.alpinelinux.org/alpine/edge/main]
OK: 5732 distinct packages available
/ # apk add go
ERROR: unsatisfiable constraints:
  go (missing):
    required by: world[go]
```

**Comment by miry** [comment] 2015-12-07 10:07
Nevermind I found that I need to specify : 

```
    echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "http://dl-3.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "http://dl-5.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
```

**Comment by bddenhartog** [comment] 2015-12-07 20:11
@miry yes, your issue was simply the repositories being incorrect -- glad you got that figured out!

@trompx can you post the contents of your local `repositories` file that you're adding to `/etc/apk/repositories`?

**Comment by trompx** [comment] 2016-01-16 05:15
Hello @bddenhartog,

Really sorry for the delayed answer, I've been very busy and I completly forgot about it.
So in my repositories file I had :
```
http://dl-1.alpinelinux.org/alpine/v3.2/main
http://dl-2.alpinelinux.org/alpine/v3.2/main
http://dl-3.alpinelinux.org/alpine/v3.2/main
http://dl-4.alpinelinux.org/alpine/v3.2/main
http://dl-5.alpinelinux.org/alpine/v3.2/main
```

I then tried with the following as miry suggested but still getting the same error
```
http://dl-1.alpinelinux.org/alpine/edge/community
http://dl-2.alpinelinux.org/alpine/edge/community
http://dl-3.alpinelinux.org/alpine/edge/community
http://dl-4.alpinelinux.org/alpine/edge/community
http://dl-5.alpinelinux.org/alpine/edge/community
```

Then I tried the exact same config as miry with alpine edge but still no luck.
I just tried with the new alpine:3.3 with 
```
FROM gliderlabs/alpine:3.3
RUN apk --update add nginx
```

but I am still getting :
```
Step 1 : FROM gliderlabs/alpine:3.3
3.3: Pulling from gliderlabs/alpine
24e7cde1dbe9: Pulling fs layer
24e7cde1dbe9: Verifying Checksum
24e7cde1dbe9: Download complete
24e7cde1dbe9: Pull complete
Digest: sha256:5b01e1909959a792afc873c0b18a03658e38d81456a9c2ac79fd0fd2c48645f6
Status: Downloaded newer image for gliderlabs/alpine:3.3
 ---> 24e7cde1dbe9
Step 2 : RUN apk --update add nginx
 ---> Running in 1701191a8cb1
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.3/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.207234d0.tar.gz: No such file or directory
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.3/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.231b5af5.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  nginx (missing):
    required by: world[nginx]
```

**Comment by andyshinn** [comment] 2016-01-16 05:27
Can you try to open or curl http://nl.alpinelinux.org/alpine/v3.3/main/ on the host having the issue? What does the host setup look like?

**Comment by trompx** [comment] 2016-01-16 05:43
I can curl the url totally fine.
The host is a ubuntu 14.04 desktop (but I had the same problem previously on a Vagrant VM with ubuntu 14.04 server).
Docker version : 1.9.1

**Comment by bddenhartog** [comment] 2016-01-16 06:37
@trompx, since you're using alpine v3.3, here is what your `/etc/apk/repositories` file should look like:

    http://dl-1.alpinelinux.org/alpine/v3.3/main
    http://dl-2.alpinelinux.org/alpine/v3.3/main
    http://dl-3.alpinelinux.org/alpine/v3.3/main
    http://dl-4.alpinelinux.org/alpine/v3.3/main
    http://dl-5.alpinelinux.org/alpine/v3.3/main

**Comment by andyshinn** [comment] 2016-01-16 06:48
If they happen to be running Docker inside VirtualBox on Mac then they are likely running into the DNS proxy issue. See if https://github.com/boot2docker/boot2docker/issues/451#issuecomment-65432123 sounds like your issue.

**Comment by bddenhartog** [comment] 2016-01-16 06:53
@andyshinn I just saw the edit to his comment; that makes a lot of sense. Good catch!

**Comment by trompx** [comment] 2016-01-16 14:45
Hello,

First thanks again for your fast answers.

I managed to figured it out. Usually I provision my servers with ansible and I have a ferm role to configure iptables. The server I was trying to build the image on is not supposed to be a server in the cloud, more a server on my local network where I create tunnel to access specific services.

As I was not applying the ferm role, I totally forgot I had set in /etc/default/docker the --iptables=false parameter, thus resulting not having the masquerad rule and all other docker container rules (https://github.com/docker/docker/issues/13381)

I am building the image now totally fine. Sorry to made you lose some time on this..
Have a good week end.
Cheers

**Comment by franz-josef-kaiser** [comment] 2016-02-29 22:17
When you got the following error

    WARNING: Ignoring APKINDEX.xxxx.tar.gz: No such file or directory

then there's a default note in the [Alpine Linux wiki](http://wiki.alpinelinux.org/wiki/Alpine_Linux:FAQ#WARNING:_Ignoring_APKINDEX.xxxx.tar.gz):

> If you get WARNING: Ignoring APKINDEX.xxxx.tar.gz: No such file or directory while running package related tools, check your /etc/apk/repositories file if an entry points to .../v2.4/testing/. This directory is gone.
> To check the content of the repositories file

        cat /etc/apk/repositories
> or

        setup-apkrepos

Not really helpful, but better than nothing…

**Comment by paweld2** [comment] 2016-03-31 07:50
The same error can be the result of this docker issue:
https://github.com/docker/docker/issues/13381

**Comment by boxxxie** [comment] 2016-04-06 19:35
I'm getting this error with rkt

**Comment by ShamariFeaster** [comment] 2016-04-21 20:20
This may or may not be related but I was getting this error when running docker on my Raspberry pi 3 and it turns out uverse was blocking my outgoing connection to the repo because "router behind router" protection was enabled on my gateway.

**Comment by mishak87** [comment] 2016-05-23 14:09
I just got same error. Repository changed to from `http://dl-4.alpinelinux.org/` to `http://dl-cdn.alpinelinux.org/`. 
Why isn't old DNS record pointed to new location?

**Comment by kaicataldo** [comment] 2016-05-23 16:00
@mishak87 Seeing this too

**Comment by oryband** [comment] 2016-05-30 12:32
this issue is back

**Comment by Skarlso** [comment] 2016-06-07 19:20
Why isn't Alpine linux's own repository in the repositories file? 😨 

Adding this into the repositories worked for most of the stuff for me:
```
http://dl-5.alpinelinux.org/alpine/v3.3/main/
http://dl-6.alpinelinux.org/alpine/v3.3/main/
```

Still can't install iptables though.

**Comment by rayyen** [comment] 2016-06-13 02:45
I am suffering this issue with v3.4.Tried everything mentioned here,however,  the only thing I can do is to download the packages I need and install it manually.

**Comment by Ehekatl** [comment] 2016-06-13 04:51
@rayyen @Skarlso @oryband ran into the same problem, my solution is simply add `--no-cache` flag and that works like a charm

**Comment by Skarlso** [comment] 2016-06-13 05:18
Also an interesting nitpick is, that the doc says that the repository URL should point to the APK_INDEX.tar.gz, where as in reality, it's pointing to the main folder and x86_64 will be autoappended.

**Comment by rayyen** [comment] 2016-06-13 05:35
@Ehekatl , your solution works great ! thanks

`alpine:/home/ray/laradock# apk add docker --no-cache
fetch http://dl-4.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-6.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
OK: 444 MiB in 61 packages
`

**Comment by jasetom** [comment] 2016-06-27 12:32
Had the same problem. It wasn't a problem with alpine at all. I just simply had to restart my virtual machine as I have changed my wifi to a different one. Silly but might help someone.

**Comment by wanjochan** [comment] 2016-07-11 03:49
@jasetom   's solution is wonderfully correct.... just 'service docker restart' the problem solved...what the f*ck...   but what if the docker is running in non-root mode.... can't tell the admin to restart....too shame...  hope the next version of docker is more stable then

**Comment by bddenhartog** [comment] 2016-07-11 03:54
@wanjochan, @jasetom: https://docs.docker.com/v1.8/articles/networking/

**Comment by bayjan** [comment] 2016-09-15 14:22
I just changed the order of main and community repos, so the resulting the /etc/apk/repositories file looks like as following:
http://dl-cdn.alpinelinux.org/alpine/v3.4/community
http://dl-cdn.alpinelinux.org/alpine/v3.4/main

And it worked. If the "main" repo was in the first line of repositories file even waiting for 30 seconds with "apk update --wait 30" didn't resolve the issue. Maybe not a solution, but might help to someone.

**Comment by ZetaoYang** [comment] 2016-10-10 07:14
I just reboot ,it is solved. 😎

**Comment by xavi-** [comment] 2016-12-01 22:44
I fixed this issue by adding `--dns 8.8.8.8 --dns 8.8.4.4` to my `DOCKER_OPTS` in `/etc/default/docker` and restarting docker.

**Comment by Raneves** [comment] 2017-01-27 16:52
this configuration works fine for me:
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.4/community" >> /etc/apk/repositories; \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.4/main" >> /etc/apk/repositories

**Comment by apmuthu** [comment] 2017-02-06 10:47
Found that networking was down. Started it with:
````
service networking restart
````

**Comment by andreasur** [comment] 2017-03-06 20:24
I had this error. It was due to some invalid invisible characters

```
RUN apk add --no-cache --virtual build-deps \
  make \
  perl \ # <--- Non-space character in this line caused the error
  gcc \
  g++ \
  git
 ...
```

Bleh.

**Comment by iomonad** [comment] 2017-04-10 07:26
Just fixed my issue by **disabling** my running **openvpn** instance. It seems to create a conflict with docker containers.
```bash
sudo service openvpn stop
```
Regards

**Comment by Katiyman** [comment] 2017-04-26 07:20
dint Under stand the root cause of the issue

**Comment by eexit** [comment] 2017-06-23 23:08
Just a `docker pull` worked. My image was too old...

**Comment by kernelpig** [comment] 2018-05-04 07:13
1. Just using mirrors.ustc.edu.cn
2. install python like this: apk add --no-cache --virtual .build-deps python
3. details as follows:
`/usr/src/app # cat /etc/apk/repositories
http://mirrors.ustc.edu.cn/alpine/v3.4/main
http://mirrors.ustc.edu.cn/alpine/v3.4/community
/usr/src/app # apk add --no-cache --virtual .build-deps python
fetch http://mirrors.ustc.edu.cn/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.ustc.edu.cn/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/9) Installing libbz2 (1.0.6-r5)
(2/9) Installing libffi (3.2.1-r2)
(3/9) Installing gdbm (1.11-r1)
(4/9) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(5/9) Installing ncurses-terminfo (6.0_p20171125-r0)
(6/9) Installing ncurses-libs (6.0_p20171125-r0)
(7/9) Installing readline (6.3.008-r4)
(8/9) Installing sqlite-libs (3.13.0-r1)
(9/9) Installing python (2.7.14-r0)
Executing busybox-1.24.2-r13.trigger
OK: 76 MiB in 31 packages`

**Comment by nazneen84** [comment] 2018-05-21 01:12
It was the corporate proxy in my case :/

**Comment by ChristophSchranz** [comment] 2018-07-16 12:09
Missing settings for the DNS-Server in docker was in my case the cause of this error:
I added the dns-servers into `/etc/docker/daemon.json`
`{
"dns": [own_dns,"8.8.8.8","8.8.8.4"]
}`
`service docker restart`
And then it worked.

**Comment by ElijahLynn** [comment] 2019-01-18 01:53
I had this issue using `alpine:latest` and trying to install `openssh-client`, using `alpine:3.4` resolved it, didn't test with other repos, used 3.4 because that is what is in the example in readme. Didn't have to update repository sources.

**Comment by dhruvasagar** [comment] 2019-02-19 03:51
I am facing this as well, some of the packages seem to fail to be installed and throw a `Protocol Error` on latest alpine, I tested and I notice that on alpine 3.7 it works fine for me however 3.8 and later give me this error. I tried playing around with changing dns, restarting docker (I am using docker for mac) and even factory reset my docker environment but none of those seem to help. Oddly however, I noticed that within my CI environment I did not face this issue, so it's something rather strange and I am unable to determine the root cause.

**Comment by vkkothawale** [comment] 2019-04-14 17:08
I am aslo new to alpine image I am facing this as well 
my cat /etc/apk/repositories file contents are as below 
http://dl-cdn.alpinelinux.org/alpine/v3.9/main
http://dl-cdn.alpinelinux.org/alpine/v3.9/community
alpine version is 3.9.3
can someone please suggest some solution 
Thanks

**Comment by dhruvasagar** [comment] 2019-04-14 18:11
@vkkothawale As of now the only solution I found was to downgrade to alpine version 3.4

**Comment by jimmyadaro** [comment] 2019-05-13 21:12
@dhruvasagar Does this still the only solution?? I'm trying to use `3.9.4` (right now it's the "latest" from Alpine) and can't install `chsh` nor `usermod` - but I can install `openssh` without any issue 🤔 

Already tried downgrading all the way down to `3.4` but still getting this error no matter what:

```text
# apk add --no-cache chsh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  chsh (missing):
    required by: world[chsh]
#
```

Same for `usermod`.

**Comment by boredazfcuk** [comment] 2019-06-24 18:50
I've been scratching my head all day because of this problem. Turns out it was a rookie mistake, but thought I'd add my solution to the list in case it helps anyone...

I was getting:
```
`ERROR: unsatisfiable constraints:
  py3-twisted (missing):
    required by: world[py3-twisted]`
```
(py3-twisted is a new addition to Alpine 3.10)

In my dockerfile I was using FROM alpine:latest and expecting it to build from Alpine 3.10.

Thing is, Alpine:latest in my local image list was only 3.9.  

docker pull alpine:latest upgraded the local alpine:latest to version 3.10 and it worked after that.

**Comment by RiskofStorm** [comment] 2019-07-24 17:51
```
FROM alpine:3.7
RUN apk --update add tmux

```
I constantly got this error, evei just for apk --update
```
Step 9/13 : RUN apk --update add tmux
 ---> Running in bac04c27db8f
/bin/sh: 1: apk: not found
The command '/bin/sh -c apk --update add tmux' returned a non-zero code: 127
```

**Comment by amanos1022** [comment] 2019-07-26 02:03
I was having this issue because I had `"iptables":false` option set in `/etc/docker/daemon.json`. Removed it, restarted docker, and the build worked as expected.
