### ISSUE TITLE
update-ca-certificates fails

### ISSUE THREAD

**Issue by BrianHicks** [gliderlabs/docker-alpine#30] opened 2015-05-05 12:32 UTC
When run under Docker, `update-ca-certificates` (from the package `ca-certificates`) fails with the line . All the information I can find seems to suggest it's a locale issue but the system profile seems to have the correct information. Any ideas?

The failure:

```
bash-4.3# update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```

**Comment by andyshinn** [comment] 2015-05-05 16:38
That isn't necessarily a failure. It is just saying "the ca-certificates.crt file has multiple certificates so we are not considering it to be symlinked". What is the actual problem here? Do you have an example I can try to reproduce?

**Comment by BrianHicks** [comment] 2015-05-05 16:48
sure, [CiscoCloud/nginx-consul](https://github.com/CiscoCloud/nginx-consul) (currently on the Docker registry as asteris/nginx-consul.) If you mount a directory with CA certs in the place mentioned in the README and run `update-ca-certificates` that happens. Am I misunderstanding the package instructions?

**Comment by andyshinn** [comment] 2015-05-05 17:36
Do you have an example CA PEM or a command I can use to generate one? I'll see if I can reproduce.

To clarify: the CA is not getting added to the `ca-certificates.crt` file regardless of the error message?

**Comment by BrianHicks** [comment] 2015-05-05 17:38
correct. I don't have one, but you can get one by running the [security-setup](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/security-setup) script in [CiscoCloud/microservices-infrastructure](https://github.com/CiscoCloud/microservices-infrastructure).

**Comment by andyshinn** [comment] 2015-05-05 20:59
Indeed, looks like an upstream bug. The line at https://github.com/alpinelinux/aports/blob/master/main/ca-certificates/update-ca-certificates#L50 should be `for key,fn in pairs(certlist) do`. I'll poke upstream and try to get a patch out.

**Comment by BrianHicks** [comment] 2015-05-05 21:14
Great, thank you!

**Comment by andyshinn** [comment] 2015-05-06 18:22
Patch submitted: http://patchwork.alpinelinux.org/patch/104/.

**Comment by andyshinn** [comment] 2015-05-06 19:40
Merged in https://github.com/alpinelinux/aports/commit/3faf2e032027ffa255f9a49f2f17c8e0239173ff. New package pushed to edge. Give it a try and let me know if we can close this.

**Comment by andyshinn** [comment] 2015-05-27 02:04
This fix should also be in Alpine 3.2 as well. We just pushed a new 3.2 tag. Reopen if still an issue.

**Closed by andyshinn** 2015-05-27 02:04 UTC
Labels: bug, upstream

**Comment by Ducatel** [comment] 2015-07-22 09:25
Issue still reproduce with the last docker image.
```
apk update && apk install curl ca-certificates \
&& curl https://www.gandi.net/static/CAs/GandiStandardSSLCA2.pem -o /usr/local/share/ca-certificates/GandiStandardSSLCA2.crt \
&& update-ca-certificates
/#  WARNING: ca-cert-GandiStandardSSLCA2.pem does not contain exactly one certificate or CRL: skipping
```

**Comment by bddenhartog** [comment] 2016-01-20 03:47
This looks to be an issue in `alpine:3.3`:

    / # apk add ca-certificates
    OK: 28 MiB in 31 packages
    / # update-ca-certificates 
    WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping

**Comment by andyshinn** [comment] 2016-01-20 03:49
What specifically is the issue?

**Comment by bddenhartog** [comment] 2016-01-20 04:31
On second inspection, I don't think `ca-certificates` is the root of [my issue](https://github.com/mumble-voip/mumble/issues/2076), but it may be worth patching anyhow (that's obviously at your discretion).

**Comment by andyshinn** [comment] 2016-01-20 04:36
The warning is just a warning. It doesn't affect anything.

**Comment by dmugtasimov** [comment] 2017-05-23 17:51
```
FROM alpine:3.5

RUN apk add --no-cache ca-certificates && \
    update-ca-certificates
```

`WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping`

The message says that something is skipped. It makes an impression that user get incomplete set of root certificates. Could you, please, rephrase, remove or fix this message, so people are not getting confused about the message?

**Comment by andyshinn** [comment] 2017-05-23 18:04
This should be brought up on http://bugs.alpinelinux.org/projects/alpine/issues. It comes from the utility in the `ca-certificates` package at https://git.alpinelinux.org/cgit/aports/tree/main/ca-certificates/c_rehash.c#n210. I agree, the warning could be better or ignored altogether if the file is `ca-certificates.crt`.

**Comment by adolphlwq** [comment] 2017-07-23 17:25
+1

**Comment by bddenhartog** [comment] 2017-07-23 17:36
@adolphlwq, your "+1" comment doesn't really give us any new information.

If you're experiencing the same issue, have none of the above comments helped? As @andyshinn noted two full moons ago, this issue doesn't really belong here.

**Comment by pedromanoel** [comment] 2017-12-28 17:20
@andyshinn mentioned that this is just a warning and shouldn't affect anything. However, `update-ca-certificates` is exiting with code '1', and I took some time to find out why my command list was failing...

**Comment by sergeyklay** [comment] 2018-03-10 10:36
What about this guys:
```dockerfile
FROM alpine:3.7

RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        ca-certificates \
    && update-ca-certificates 2>/dev/null || true
```

**Comment by danielpalstra** [comment] 2018-03-28 09:28
I think it's great for a workaround, but the command shouldn't exit 1 on a warning. Or we should be able to ignore warnings. I have implemented this workaround in my Dockerfile, but I don't think I can really assume  that everything is fine certificate wise anymore.

**Comment by Lauriy** [comment] 2019-01-17 10:34
This is still a problem.

**Comment by butla** [comment] 2019-03-13 12:04
This still doesn't work (produces the warning, doesn't add stuff to /etc/ssl/certs/ca-certificates.crt) with alpine 3.9:

```
COPY ca-cert-XXX.pem /etc/ssl/certs/
update-ca-certificates
```
my workaround:
```
COPY ca-cert-XXX.pem /etc/ssl/certs/
RUN cat ca-cert-XXX.pem >> /etc/ssl/certs/ca-certificates.crt
```

@andyshinn so shouldn't the issue be reopened?

**Comment by jharshman** [comment] 2019-03-22 19:25
Just ran into this today, not able to add a CA.

**Comment by rvsrinivas** [comment] 2019-03-26 22:51
This is still a problem

**Comment by da3mon-01** [comment] 2019-03-27 15:01
How I can verify that my cert has been actually imported into the ca-certs?

**Comment by butla** [comment] 2019-03-27 15:13
@da3mon-01 it should get appended to /etc/ssl/certs/ca-certificates.crt

**Comment by ibrt** [comment] 2019-04-04 14:25
I think there are two separate issues here, stemming from the same root cause. It looks like `update-ca-certificates` skips any PEM file in `/usr/local/share/ca-certificates` if it contains more than one certificate. 

If you only get a warning about `ca-certificates.crt` it's harmless, but if you just added a new PEM file and you want to import it (e.g. the RDS certificate chain), you will get a warning for that file, and the certificates will not be imported. Confusing.

The workaround I found is to split the new PEM file into individual files first, one per certificate:

```
cd "/usr/local/share/ca-certificates" && curl "https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem" | csplit -f "rds-" - '/-----BEGIN CERTIFICATE-----/' '{*}'`
```

**Comment by cmcarey** [comment] 2019-08-16 13:54
Months later, still a problem.  Issue should _not_ be closed.

**Comment by MattFriedman** [comment] 2019-09-20 15:35
WARNING: nothing is wrong

The message above should be either reworded so it makes sense or removed. It's useless and people, like me, are wasting their time trying to figure out what it means.

**Comment by Aeres-u99** [comment] 2019-12-20 20:15
Apparently, I am also experiencing the very same issue. I dont know how to approach to solve it.
```
root@animeVPS:~# wget https://rclone.org/install.sh 
Connecting to rclone.org (5.153.250.7:443)
wget: SSL/TLS certificate is not being validated!

root@animeVPS:~# update-ca-certificates 
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping

root@animeVPS:~# apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86/APKINDEX.tar.gz
v3.5.3-45-g195c4dea45 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
v3.5.3-44-g08ec10f083 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]
OK: 7924 distinct packages available

root@animeVPS:~# apk add ca-certificates
OK: 468 MiB in 138 packages

root@animeVPS:~# update-ca-certificates 
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping

# ---- Not a server side Issue? ----

root@animeVPS:~# wget --no-check-certificate https://rclone.org/install.sh 
Connecting to rclone.org (5.153.250.7:443)
wget: error getting response: Connection reset by peer

#--- this might be unrelated but still worth taking a look? ---

root@animeVPS:~# apk add curl-dev
ERROR: unsatisfiable constraints:
  libressl-dev-2.4.4-r0:
    conflicts: openssl-dev-1.0.2q-r0[pc:libcrypto=2.4.4] openssl-dev-1.0.2q-r0[pc:libssl=2.4.4] openssl-dev-1.0.2q-r0[pc:openssl=2.4.4]
    satisfies: libssh2-dev-1.7.0-r2[libressl-dev] libssh2-dev-1.7.0-r2[pc:libcrypto] libssh2-dev-1.7.0-r2[pc:libssl] curl-dev-7.61.1-r1[libressl-dev]
  openssl-dev-1.0.2q-r0:
    conflicts: libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2q] libressl-dev-2.4.4-r0[pc:libssl=1.0.2q] libressl-dev-2.4.4-r0[pc:openssl=1.0.2q]
    satisfies: world[openssl-dev] libssh2-dev-1.7.0-r2[pc:libcrypto] libssh2-dev-1.7.0-r2[pc:libssl]


```

**Comment by janschloss** [comment] 2020-02-10 11:37
Problem still exists

**Comment by Tatukis** [comment] 2020-02-18 19:55
`/ # mv DigiCertSHA2SecureServerCA.crt.pem /usr/local/share/ca-certificates/DigiCertSHA2SecureServerCA.crt
/ # update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
`
I'm running this in the image itself and get that warning, and I don't know if my certificates are updated or not.

**Comment by Lauriy** [comment] 2020-02-18 20:08
Just don't use Alpine & Docker. Nobody cares if you shave 100 MB off an image. 2 hours of your work is a terabyte disk.

**Comment by GabLeRoux** [comment] 2020-02-27 21:22
Message is misleading, but it's only a warning. It doesn't mean it failed to run `update-ca-certificates` as according to exit code, it did succeed if it continues to next step.

In case you have access to `python` inside your docker image and really want to make sure the certificate was correctly added, here's an example with a verification.

```Dockerfile
ARG CA_BUNDLE_SOURCE=https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
ARG CA_BUNDLE_DESTINATION=/usr/local/share/ca-certificates/rds-combined-ca-bundle.pem

ADD $CA_BUNDLE_SOURCE $CA_BUNDLE_DESTINATION
RUN update-ca-certificates
RUN python -c "x=open('$CA_BUNDLE_DESTINATION').read(); y=open('/etc/ssl/certs/ca-certificates.crt').read(); exit(0) if x in y else exit(-1)"
```

_Above python trick comes from https://unix.stackexchange.com/a/114882/63222 and was adapted to fail if file doesn't contain other file. There are probably much better ways out there._

At this point, it's probably easier to append the bundle directly to `/etc/ssl/certs/ca-certificates.crt` like this:

```Dockerfile
ARG CA_BUNDLE_SOURCE=https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
ARG CA_BUNDLE_DESTINATION=/usr/local/share/ca-certificates/rds-combined-ca-bundle.pem

ADD $CA_BUNDLE_SOURCE $CA_BUNDLE_DESTINATION
RUN cat $CA_BUNDLE_DESTINATION >> /etc/ssl/certs/ca-certificates.crt
```

**Comment by bbolli** [comment] 2020-04-16 18:20
I have looked into this a bit closer.

The reason for this warning is the `c_rehash` program that runs at the very end of `update-ca-certificates`. Its purpose is to (re)generate the hash symlinks in `/etc/ssl/certs`. This is only possible if a file contains a single certificate (or revocation list).

When `c_rehash` encounters`ca-certificates.crt` which contains the concatenation of all certificates, it rightly complains that this file cannot be hashed. But as noted above, this is indeed just a warning and the update of the certificates did work.

Source: https://git.alpinelinux.org/ca-certificates/

I suggest to close this issue.

**Comment by nikskiz** [comment] 2020-05-28 04:28
It may be a warning, but why does the message include `skipping`. This is misleading as others have mentioned.

**Comment by bbolli** [comment] 2020-05-28 10:06
> but why does the message include `skipping`

Because the file mentioned contains more than one certificate and thus can't be hashed. This is output from `c_rehash`.

**Comment by franz-josef-kaiser** [comment] 2021-01-04 15:52
The issue still persists. I get the warning both for a cert and the store file:

**Reproduce:**
1. Try to install cert
    ```shell
     /etc/ssl/certs # update-ca-certificates 
    WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
    WARNING: ca-cert-<DOMAIN>.<TLD>.pem does not contain exactly one certificate or CRL: skipping
    ```

1. Checking, **if the cert was added** to the store: The solution by @GabLeRoux is good, but probably an overkill. There's no need for `python` in your container: Alpine Linux ships with `comm` (a reverse `diff`):
    ```shell
    comm -12 /etc/ssl/certs/ca-cert-<DOMAIN>.<TLD>.pem  /etc/ssl/certs/ca-certificates.crt
    ```
    The result, that you should see if the cert was added to the `ca-certificates.crt`-store is:
    ```
    -----BEGIN CERTIFICATE-----
    ```
    …or nothing. If you see a complete cert, then it tells you that the cert wasn't successfully added.
    In my case, the cert was added, still the `WARNING` about the single cert is there.
    
1. Try to fetch from a local URl:
    ```shell
   /etc/ssl/certs # wget -qO- http://127.0.0.1/nginx_status 
   ssl_client: <DOMAIN>.<TLD>: certificate verification failed: unable to get local issuer certificate
   wget: error getting response: Connection reset by peer
   ```
1. Ignore the cert for a `wget` call. Does not work for other connections where you do not have access to request args:
    ```shell
   /etc/ssl/certs # wget --no-check-certificate -qO- http://127.0.0.1/nginx_status 
   Active connections: 1 
   server accepts handled requests
    10 10 8 
   Reading: 0 Writing: 1 Waiting: 0
      ```

**Comment by rustyx** [comment] 2021-01-09 14:59
@franz-josef-kaiser that is another issue, your cert `ca-cert-<DOMAIN>.<TLD>.pem` is skipped from rehashing because it didn't contain exactly one cert or CRL (like the message says).

`ca-certificates.crt` isn't really used. Instead a certificate is looked up by its hash - a symlink like `fe8a2cd8.0`. These symlinks are created by the program `c_rehash` which is invoked as part of `update-ca-certificates`. And that's where the warnings come from.

The warning about the bundle is really just a warning though. It's because `update-ca-certificates` is writing the bundle before invoking `c_rehash /etc/ssl/certs/`. I've submitted a [**PR\#1**](https://gitlab.alpinelinux.org/rustyx/ca-certificates/-/merge_requests/1) to Alpine to address this. Just tested and seems to be working fine.

```
~ # update-ca-certificates
~ #
```

**Comment by franz-josef-kaiser** [comment] 2021-01-11 21:50
@rustyx Thanks for clarifying that (and submitting the PR to Alpine@GitLab)

> Instead a certificate is looked up by its hash - a symlink like `fe8a2cd8.0`.

**Comment by yellowmegaman** [comment] 2021-08-04 10:10
Still a problem, wow.

**Comment by 1in9e** [comment] 2021-08-05 06:01
A problem.
FROM python:3.8-alpine
`bash-5.1# update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping`

**Comment by dualmacops** [comment] 2021-08-26 12:01
From Home Assistant core-2021.8.8

bash-5.1# update-ca-certificates 
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping

**Comment by franz-josef-kaiser** [comment] 2021-08-28 22:53
The following warning is not an error. It's just how the command works: It checks all certs, including the main file, which contains more than one file. The error message just could be improved:
```
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```

**Comment by lhzw** [comment] 2022-03-04 03:39
It's much better if it outputs the result as normal linux, then we know the cert has been added, so it's just a warning. At first glance at this warning and no other outputs, I thought it did not add the cert.
```
update-ca-certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

updates of cacerts keystore disabled.
done.
```

**Comment by journaux** [comment] 2022-03-14 11:48
haha. oh my. still an issue all these years later.

**Comment by JonathonReinhart** [comment] 2022-03-14 13:53
> haha. oh my. still an issue all these years later.

@vitruvvius What have *you* contributed to fixing the issue?

**Comment by amoona6** [comment] 2022-03-26 22:30
First-time poster! Please excuse any informal etiquette.

I spent 2-hours troubleshooting a similar issue in Ubuntu, but was able to come up with a solution (my thought is maybe my findings could be helpful for others). Firstly, I started from scratch: 

- removed all entries and files related to my .crt file (`find / -type f -name "[certname].*"`) 
- ran `sudo update-ca-certificates --fresh`
- follow up on any loose ends (had to remove one line from  `/etc/ca-certificates.conf`)

Important:

- Follow all the usual steps, up until running `update-ca-certificates`
-  Before running the updater, set the CA certificate file permissions to 644 (`sudo chmod 644 ./file.crt`). Originally, in my case, my certificate had 755 permissions
- Run `sudo update-ca-certificates`

After running the update, the certificate was available.

**Comment by huchim** [comment] 2022-06-14 16:46
Hi!

This is not Alpine, but I figured out my certificates files was using UTF-8 BOM and saved without BOM and certificates was included without warnings.

```Dockerfile
FROM node:14
COPY CPTTRootCertificateAuthority.crt /usr/local/share/ca-certificates/
COPY CPTTIntermediateCertificate.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

Maybe this comment is not useful, but works for me.

**Comment by enderandpeter** [comment] 2022-07-19 23:51
For what it's worth, the exit code for this warning now appears to be 0, fortunately:

```bash
bash-5.1# update-ca-certificates --fresh
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
bash-5.1# echo $?
0
```

**Comment by JoelTrain** [comment] 2022-11-28 17:35
I see this "warning" `does not contain exactly one certificate or CRL` 
and then immediately try to use my supposedly newly trusted certificate to make a TLS connection using curl and it fails
`curl: (60) SSL certificate problem: self signed certificate in certificate chain`

So in my case it does seem the addition to the trust store was indeed skipped as well.
I guess results may vary depending on versions or some other lurking variable.

**Comment by rwjack** [comment] 2023-02-06 21:30
It seems the container recognizes my CA (docker:dind - which is alpine basically), and running `update-ca-certificates` shows nothing within the container, but the error everyone is talking about is constantly showing up on my gitlab CI jobs.
`WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping`

Fixed:
runner: `config.toml`:
```
[runners.docker]
#volumes = ["/cache", "/opt/gitlab-runner/config/certs/ca.crt:/etc/gitlab-runner/certs/ca.crt:ro"]
volumes = ["/cache"]
```

The runner tries to be smart and if `/etc/gitlab-runner/certs/ca.crt` is mapped as a volume, it will constantly try to inject it, hence the error messages.

**Comment by Acerinth** [comment] 2023-02-23 13:56
@rwjack I have the same issue in GitLab CI - only I'm not mounting it with Runner config, but tried installing during a job directly inside a docker-dind image:
```
services:
    - name: docker:20.10-dind
      command:
        - /bin/sh
        - -c
        - echo "$CI_SERVER_TLS_CA_FILE" > /usr/local/share/ca-certificates/my-ca.crt && update-ca-certificates && dockerd-entrypoint.sh || exit
```

Did you found a workaround, apart from creating your own dind image with injected CA's certs?

**Comment by rwjack** [comment] 2023-02-23 15:23
@Acerinth I'm not sure honestly, though I managed to evade that warning somehow. I still mount the CA in the gitlab-runner `config.toml` as shown above, but I also build my own dind image.

```
FROM docker:dind

COPY CA.pem /usr/local/share/ca-certificates/ca.crt # <- IMPORTANT to be *.crt
RUN update-ca-certificates --fresh
```

**Comment by JoelTrain** [comment] 2023-03-24 23:15
Does anyone have a script that splits a single .pem file with multiple certificates in it into individual files?
That way I can actually import and trust them without the warning/skip?

I am encountering this "warning" again and would like all the certificates in my file to actually be imported and trusted.

**Comment by JoelTrain** [comment] 2023-03-24 23:21
Also, I am sorry. I think this is the wrong repo to report this issue.
So if you can point me to where to report the problem to the correct source repo, that would be appreciated as well.

I think skipping certs in a file should be an error, not a warning. (whether they are actually skipped or not is up for debate in this thread, but in some cases the warning about skipping actually does mean they are skipped and not added to the trust store)

**Comment by khmarochos** [comment] 2025-07-25 06:45
> Does anyone have a script that splits a single .pem file with multiple certificates in it into individual files? That way I can actually import and trust them without the warning/skip?
> 
> I am encountering this "warning" again and would like all the certificates in my file to actually be imported and trusted.

Like this one?

```bash
#!/bin/bash
set -euo pipefail

# Exit if CA file not provided
[[ -z "${CI_SERVER_TLS_CA_FILE:-}" ]] && exit 0

# Detect OS family
if [[ -f /etc/redhat-release ]]; then
    OS_FAMILY="redhat"
    CA_DIR="/etc/pki/ca-trust/source/anchors"
    UPDATE_CMD="update-ca-trust extract"
    PKG_MGR="yum install -y ca-certificates"
elif [[ -f /etc/debian_version ]]; then
    OS_FAMILY="debian"
    CA_DIR="/usr/local/share/ca-certificates"
    UPDATE_CMD="update-ca-certificates --fresh"
    PKG_MGR="apt-get update && apt-get install -y ca-certificates"
elif [[ -f /etc/alpine-release ]]; then
    OS_FAMILY="alpine"
    CA_DIR="/usr/local/share/ca-certificates"
    UPDATE_CMD="update-ca-certificates"
    PKG_MGR="apk add --no-cache ca-certificates"
else
    echo "Unsupported OS" >&2
    exit 1
fi

# Install CA certificates package
eval "$PKG_MGR"

# Create CA directory if needed
mkdir -p "$CA_DIR"

# Split and process certificates
MODE="${CI_SERVER_TLS_CA_FILE_SPLIT_MODE:-all}"
awk -v mode="$MODE" -v dir="$CA_DIR" '
    /^-----BEGIN CERTIFICATE-----$/ { cert=""; n++ }
    { cert = cert $0 "\n" }
    /^-----END CERTIFICATE-----$/ {
        certs[n] = cert
    }
    END {
        if (mode == "first") {
            print certs[1] > dir"/custom-ca-1.crt"
        } else if (mode == "last") {
            print certs[n] > dir"/custom-ca-" n ".crt"
        } else {
            for (i=1; i<=n; i++) {
                print certs[i] > dir"/custom-ca-" i ".crt"
            }
        }
    }
' "$CI_SERVER_TLS_CA_FILE"

# Update CA trust
$UPDATE_CMD
```
